### ISSUE TITLE
Issue with Datables: Lesson 078 Data tables plug in 

### ISSUE THREAD

**Issue by GFOX91** [mosh-hamedani/vidly-mvc-5#74]
Hi,

I have followed the steps exactly in this lesson, however the datable has not been applied to my customer table. I have reviewed the all my code and have checked for typos and it all looks like its correct. I have also updated bootstrap and datat ables plug in and I am still getting the same results. Can anyone help with this? I have attached the relevant code files from my project.

Thanks,
![Customers table](https://user-images.githubusercontent.com/51232749/58701398-b36d5580-839a-11e9-94e4-3a981a9787cd.PNG)

![bundle config](https://user-images.githubusercontent.com/51232749/58701539-25459f00-839b-11e9-9c57-62917f586e0a.PNG)

![Layout_cshtml](https://user-images.githubusercontent.com/51232749/58701614-4d350280-839b-11e9-99c0-1d866eb62160.PNG)

![Index](https://user-images.githubusercontent.com/51232749/58701660-6a69d100-839b-11e9-88c5-1b109cde0130.PNG)

**Comment by muswilam** [comment]
your table in the view must be full structured with table tags like <thead> , <tbody> to make DataTable works effiently

**Comment by GFOX91** [comment]
This was exactly the issues, I was missing the <Thead> and <Tbody> tags.

Thanks for the help!

**Comment by vivpoojari5p** [comment]
Actually I've also followed all the exact steps, and I've structured my table properly as well, checked with the github source code for Index.cshtml. But still my datatables won't work. I'm not sure what the other user meant by "table in the view must be full structured with table tags like , to make DataTable works effiently", what tag are they talking about? I don't see any missing tags in my code, still it won't work. Already wasted a lot of time resolving bundling issues with jquery and bootstrap because newer versions of bootstrap have 2 issues. In case anyone's stuck - 
you have to create separate bundle for including /scripts/bootstrap.js, and instead of saying new ScriptBundle you have to say new Bundle for whatever reasons.

Update: I messed up, typed Datatables( ) instead of Data**T**ables( )
