### ISSUE TITLE
create database when downloading later commit

### ISSUE THREAD

**Issue by CS-Jensen** [mosh-hamedani/vidly-mvc-5#76]
I have encountered several issues with this project now and one of them is; how can I download a commit of the project and create the database as it is supposed to be for that commit? I can't find an answer here nor by googling it

**Comment by iHamzaKhanzada** [comment]
> Question 1. how can I download a commit of the project?

Go to https://github.com/mosh-hamedani/vidly-mvc-5 and click on the commits tab. Then instead of clicking on the commit name, click on Browse the repository at this point in the history button (See screenshot attached) with <> symbol to the right side of the commit name/message, and finally on the Download ZIP button that comes when you click Clone or Download button.

![image](https://user-images.githubusercontent.com/34980386/60517215-b7bdc300-9cf8-11e9-8c3b-cdfd4e581dd7.png)


Now when you have downloaded the Zip file and extracted it, and you want to 

> Question 2. create the database as it is supposed to be for that commit

Now for the restoration part, its quite long so be patient and follow

1. When you have downloaded the zip file of that specific commit, extract it and make sure to rename the folder to vidly-mvc only rather than vidly-mvc-<commitguid>

2. when you have renamed the solution folder, open the sln. file in visual studio and go to Tools > nuget package manager > package manager console

3. In package manager console restore the packages by clicking on restore button

4. After restoring packages Clean solution using Ctrl + Shift + B

5. Close the visual studio and open visual studio again and open the project 

6. in web.config file, in connection strings, change the data source to (LocalDb)\MSSQLLocalDB rather than (LocalDb)\v11.0

7. Save web.config file and in Package manager console run the following command 'update-database'

8. Build the solution and run :)

**Comment by CS-Jensen** [comment]
Thank you very much :)
